###
# This file configures the project "Piper" pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
#    https://sap.github.io/jenkins-library/
#
# This is a YAML-file. YAML is an indentation-sensitive file format. Please make sure to properly indent changes to it.
###



### General project setup
general:
  productiveBranch: 'chapter5-tms-upload'
  inferBuildTool: true
  verbose: true

### Step-specific configuration
steps:
  mavenExecute:
    dockerImage: devxci/mbtci:1.0.14

  artifactPrepareVersion:
    versioningType: cloud_noTag

  cloudFoundryDeploy:
    cloudFoundry:
      org: 'ic-adv-dev-cf'
      space: 'Dev - CI/CD Trainer'
      credentialsId: 'cf-credentials-xx'

  tmsUpload:
    nodeName: 'TEAM_XXXX_PROD'
    credentialsId: 'ctms-servicekey-xx'
    customDescription: 'team xx: cTMS upload from pipeline'
  
### Stage-specific configuration
stages:
  'Central Build':
    buildExecute : true

  'Additional Unit Tests':
    karmaExecuteTests: true

  'Acceptance':
    cloudFoundryDeploy: false

  'Confirm':
    manualConfirmation: false

  'Release':
    cloudFoundryDeploy: true
    tmsUpload: true
